spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  security:
    user:
      name: buzz
      password: infinity



taco:
  orders:
    pageSize: 10
logging:
  level:
    tacos: DEBUG
---
spring:
  profiles: prod

logging:
  level:
    root: WARN